.TH "WORDLISTCTL" "1" "" "" ""
.SH NAME
.PP
wordlistctl \- Fetch, install and search wordlist archives from websites.
.SH SYNOPSIS
.PP
wordlistctl [\fB-h\fR] [\fB-v\fR] {\fBfetch\fR,\fBsearch\fR,\fBlist\fR}
.SH DESCRIPTION
.PP
Script to fetch, install, update and search wordlist archives from websites offering wordlists with more than 6300 wordlists available.
.SH OPTIONS
.PP
.HP
\fBfetch\fR           fetch wordlists.
.HP
\fBsearch\fR          search wordlists [default: \fI\,/usr/share/wordlists\/\fP].
.HP
\fBlist\fR            list wordlists.
.HP
\fB\-h, --help\fR     show this help message and exit.
.HP
\fB\-v, --version\fR  show program's version number and exit.
.PP
.SH FETCH OPTIONS
.PP
.HP
\fB-h, --help\fR                  show fetch help message
.HP
\fB-b, --basedir\fR <basedir>     wordlists base directory
.IP
                     (default: \fI/usr/share/wordlists\/\fP)
.HP
\fB-d, --decompress\fR            decompress and remove archive
.HP
\fB-g, --group\fR <group>         wordlist group to fetch
                     Available Groups are:\&
                         usernames
                         passwords
                         discovery
                         fuzzing
                         misc
.HP
\fB-l, --wordlist\fR <wordlist>   wordlist to fetch
.HP
\fB-u, --useragent\fR <useragent> fetch user agent [default: wordlistctl/v0.8.9]
.HP
\fB-w, --workers\fR <workers>     download workers [default: 10]
.PP
.SH SEARCH OPTIONS
.PP
.HP
\fB-h, --help\fR                  show fetch help message
.HP
\fB-b, --basedir\fR <basedir>     wordlists base directory
.IP
                     [default: \fI/usr/share/wordlists\/\fP]
.HP
\fB-l, --local\fR                 search local archives
.PP
.SH LIST OPTIONS
.PP
.HP
\fB-h, --help\fR                  show fetch help message
.HP
\fB-g, --group\fR <group>         list als wordlists in group
                     Available Groups are:\&
                         usernames
                         passwords
                         discovery
                         fuzzing
                         misc

