.TH "WORDLISTCTL" "1" "" "" ""
.SH NAME
.PP
wordlistctl \- Fetch, install and search wordlist archives from websites.
.SH SYNOPSIS
.PP
wordlistctl [\fB-h\fR] [\fB-v\fR] {\fBfetch\fR,\fBsearch\fR,\fBlist\fR}
.SH DESCRIPTION
.PP
Script to fetch, install, update and search wordlist archives from websites offering wordlists with more than 6300 wordlists available.
.SH OPTIONS
.PP
.HP
\fBfetch\fR         fetch wordlists.
.HP
\fBsearch\fR        search wordlists (default: \fI\,/usr/share/wordlists\/\fP).
.HP
\fBlist\fR          list wordlists.
.HP
\fB\-h\fR            show this help message and exit.
.HP
\fB\-v\fR            show program's version number and exit.
.PP